name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{github.token}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache dependencies
        uses: actions/cache@v3
        id: npm-cache
        env:
          cache-name: npm-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Install Playwright (for MermaidJS)
        run: npx playwright install --with-deps chromium

      - name: Build Website
        run: npm run build

      - name: Upload Built Website
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist/

  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{github.token}}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/download-artifact@v3
        name: Retrieve output from build step
        with:
          name: github-pages
          path: ./website-build

      - run: |
          mkdir -p ./dist
          tar -xf ./website-build/artifact.tar -C ./dist/ --strip-components=1
        name: Decompress build step output

      - name: Cache dependencies
        uses: actions/cache@v3
        id: npm-cache
        env:
          cache-name: npm-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium firefox

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
